[package]
name = "fft"
version = "0.1.0"
authors = ["Olivier Lefebvre <lefebvre.olivier11@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
angular = "0.1.1"
float-cmp = "0.8.0"
plotters = "^0.2.15"
